Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 41

Metrics/ClassLength:
  Max: 128

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 34

Metrics/ParameterLists:
  Max: 7

Metrics/PerceivedComplexity:
  Max: 13

Style/Documentation:
  Enabled: false

Style/MutableConstant:
  Exclude:
    - 'lib/behoimi.rb'
    - 'lib/booru/base.rb'
    - 'lib/danbooru.rb'
    - 'lib/testbooru.rb'
    - 'lib/konachan.rb'
    - 'lib/yandere.rb'

Style/OptionalBooleanParameter:
  Exclude:
    - 'lib/booru/base.rb'
