require:
  - rubocop-performance

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bundle/**/*'
    - 'vendor/**/*'
    - 'images/**/*'
  TargetRubyVersion: 2.7

Style/FrozenStringLiteralComment:
  Enabled: false
