require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bundle/**/*'
    - 'vendor/**/*'
    - 'images/**/*'
  TargetRubyVersion: 2.7
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false
