inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bundle/**/*'
    - 'vendor/bundle/**/*'
    - 'images/**/*'
    - 'features/**/*'
  TargetRubyVersion: 2.3

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120
