Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 42

Metrics/ClassLength:
  Max: 128

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/MethodLength:
  Max: 45

Metrics/ParameterLists:
  Max: 7

Metrics/PerceivedComplexity:
  Max: 14

Style/Documentation:
  Enabled: false

Style/MutableConstant:
  Exclude:
    - 'lib/behoimi.rb'
    - 'lib/booru/base.rb'
    - 'lib/danbooru.rb'
    - 'lib/testbooru.rb'
    - 'lib/konachan.rb'
    - 'lib/yandere.rb'
