dist: trusty
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libmagic-dev curl wget
language: ruby
cache: bundler
bundler_args: --without development
script:
  - bundle exec rake spec:ci
  - bundle exec rake rubocop
rvm:
  - 2.5.1
  - 2.4.4
  - 2.3.7
  - 2.2.10
  - rubinius-3
gemfile:
  - Gemfile
notifications:
  recipients:
    - xeron.oskom@gmail.com
matrix:
  fast_finish: true
  allow_failures:
    - rvm: rubinius-3
