dist: bionic
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libmagic-dev curl wget
  - gem update bundler
language: ruby
cache: bundler
bundler_args: --without development
script:
  - bundle exec rake spec:ci
  - bundle exec rake rubocop
rvm:
  - 3.0
  - 2.7
  - 2.6
gemfile:
  - Gemfile
notifications:
  recipients:
    - xeron.oskom@gmail.com
matrix:
  fast_finish: true
  allow_failures:
    - rvm: 3.0
