dist: bionic
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libmagic-dev curl wget
  - gem update bundler
language: ruby
cache: bundler
bundler_args: --without development
script:
  - bundle exec rake spec:ci
  - bundle exec rake rubocop
rvm:
  - 2.6.5
  - 2.5.7
  - 2.4.8
  - rubinius-4
gemfile:
  - Gemfile
notifications:
  recipients:
    - xeron.oskom@gmail.com
matrix:
  fast_finish: true
  allow_failures:
    - rvm: rubinius-4
